### ISSUE TITLE
Got 403 for configuration service url 

### ISSUE THREAD

**Issue by saurabhPV** [appbaseio/reactivesearch-api-docker#2]
I am using dev mode `docker-compose -f docker-compose-with-elasticsearch.yaml up -d` 
I can see `nginx`  and all other containers are running other than arc service because it doesn't have env I suppose since it throws an error for the same
![image](https://user-images.githubusercontent.com/15213067/100877954-88a01800-34cf-11eb-8951-dcc7c6d9cef5.png)
but then 403 
![image](https://user-images.githubusercontent.com/15213067/100877876-69a18600-34cf-11eb-8553-7eb21e3eb59c.png)

**Comment by lakhansamani** [comment]
@saurabhPV can you share the logs of docker container of nginx + arc
Ref for logs command: https://docs.docker.com/engine/reference/commandline/logs/

Also do check if any other service is not running on port 80

**Comment by saurabhPV** [comment]
thanks @lakhansamani for quick response!
I can see there is no process running on 80 when I stopped the containers - also it would not have start the container had the port been occupied.   

![image](https://user-images.githubusercontent.com/15213067/100882556-5691b480-34d5-11eb-9822-7f0294e4c6f0.png)
 
these are the logs from arc service 
![image](https://user-images.githubusercontent.com/15213067/100882968-c99b2b00-34d5-11eb-8dba-8e932d036c0e.png)

these are the logs from nginx service 
![image](https://user-images.githubusercontent.com/15213067/100883094-efc0cb00-34d5-11eb-97b7-6951c74e4ec4.png)

Also I tried to access the nginx access and error logs  from `\var\logs\nginx` and I don't see any entry there either when I try to access `http://localhost/`

**Comment by lakhansamani** [comment]
@saurabhPV seems some issues with windows and docker networking. Till we resolve this for windows can you try following setup mentioned below.

* Copy following content in `docker-compose-raw.yml` the `arc-dockerized` folder
* Relace APPBASE_ID with your APPBASE_ID in appbase container env config
* Run the setup using `docker-compose -f docker-compose-raw.yml -up`

```
version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - network.publish_host=_local_
      - network.host=_local_,_site_
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - elasticsearch
  appbase:
    container_name: appbase
    image: appbaseio/arc:7.37.0
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - USERNAME=foo
      - PASSWORD=bar
      - SET_SNIFFING=false
      - APPBASE_ID=YOUR_APPBASE_ID
      - ES_CLUSTER_URL=http://elasticsearch:9200
    volumes:
      - "appbase-data:/appbase-data"
    ports:
      - 8000:8000
    networks:
      - elasticsearch
  fluentbit:
    image: fluent/fluent-bit:1.5
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - "appbase"
    restart: always
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./parser.conf:/fluent-bit/etc/parser.conf"
      - "appbase-data:/appbase-data"
volumes:
  appbase-data:
    external: false
networks:
  elasticsearch:
    driver: bridge

```
